services:
  backend:
    container_name: kitchenmanager-backend
    build:
      context: ./backend-kitchenmanager
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - "./backend-kitchenmanager:/app"
      - "~/.m2:/root/.m2"  # Monta o cache do Maven
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/kitchenmanagerdb
      SPRING_DATASOURCE_USERNAME: gabma
      SPRING_DATASOURCE_PASSWORD: gabma
    depends_on:
      postgresql:
        condition: service_healthy

  frontend:
    container_name: kitchenmanager-frontend
    build:
      context: ./frontend-kitchenmanager
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./frontend-kitchenmanager:/app"
      - /app/node_modules
    depends_on:
      - backend
      - postgresql

  postgresql:
    container_name: postgresql
    image: "postgres"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=password
      - POSTGRES_USER=gabma
      - POSTGRES_PASSWORD=gabma
      - POSTGRES_DB=kitchenmanagerdb
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gabma -d kitchenmanagerdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
